apiVersion: temporal.io/v1
kind: Temporal
metadata:
  name: temporal
spec:
  admintools:
    enable: true
  db_host: temporal-db1.ce1n9s2ehuqa.us-east-1.rds.amazonaws.com
  db_port: 5432
  db_user: postgres
  driver_name: postgres
  frontend:
    enable: true
  history:
    enable: true
  instance_name: temporal-test
  matching:
    enable: true
  num_shards: 512
  plugin_name: postgres
  temporal_db_password: temporal
  web:
    enable: true
  worker:
    enable: true
